name = "MomentArithmetic"
uuid = "216cd8d6-c1f2-4f0b-a686-f7bd07ccd726"
authors = ["Ander Gray <ander.gray@liverpool.ac.uk>", "Scott Ferson <Scott.Ferson@liverpool.ac.uk>"]
version = "0.1.2"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
ProbabilityBoundsAnalysis = "cd73f0b2-6f06-11ea-242f-83a09de6a7cf"

[compat]
IntervalArithmetic = "0.18, 0.19, 0.20"
ProbabilityBoundsAnalysis = "0.2"
julia = "1"
